shell.run("rm", "armyControl")
shell.run("rm", "armySetup")
shell.run("rm", "startup")
h = fs.open("startup", "w")
h.writeLine("shell.run(\"rm\", \"armyControl\")")
h.writeLine("shell.run(\"rm\", \"armySetup\")")
h.writeLine("shell.run(\"wget\", \"https://raw.githubusercontent.com/drunkripper/CCTurtleMiningProgram/main/armySetup.lua\", \"armySetup.lua\")")
h.writeLine("shell.run(\"wget\", \"https://raw.githubusercontent.com/drunkripper/CCTurtleMiningProgram/main/armyControl.lua\", \"armyControl.lua\")")
h.close()
os.reboot()
