shell.run("rm", "armyControl.lua")
shell.run("rm", "armySetup.lua")
shell.run("rm", "startup.lua")
h = fs.open("startup.lua", "w")
h.writeLine("shell.run(\"rm\", \"armyControl.lua\")")
h.writeLine("shell.run(\"rm\", \"armySetup.lua\")")
h.writeLine("shell.run(\"wget\", \"https://raw.githubusercontent.com/drunkripper/CCTurtleMiningProgram/main/armySetup.lua\", \"armySetup.lua\")")
h.writeLine("shell.run(\"wget\", \"https://raw.githubusercontent.com/drunkripper/CCTurtleMiningProgram/main/armyControl.lua\", \"armyControl.lua\")")
h.writeLine("shell.run(\"armySetup.lua\")")
h.close()
os.reboot()
